---
name: go-test
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
permissions:
  contents: read

jobs:
  uncommitted-code-check:
    name: uncommitted-code-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Check generated deploy code
        run: make generate-deploy

      - name: Check for uncommitted changes
        run: make check-all-committed

      - name: Show the uncommitted "git diff"
        if: ${{ failure() }}
        run: git diff ; false
  go-test:
    name: go-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: go-test
        run: make containerized-test TARGET=go-test
  go-test-api:
    name: go-test-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: go-test-api
        run: make containerized-test TARGET=go-test-api
